baseurl = "/"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = ""
paginate = 5
theme = "hugo-geo"

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"

	analytics = "code-here"

	github = "https://github.com/jkpr"
	linkedin = "https://www.linkedin.com/in/jameskpringle"
	email = "jameskpringle@gmail.com"

	profilepic = "img/profile.jpg"

	title = "James K. Pringle"
	subtitle = "Blogger - Programmer - Cheetah"

	[[params.navlinks]]
	name = "About"
	url = "about"

	[[params.navlinks]]
	name = "Blog"
	url = ""

	[[params.navlinks]]
	name = "Tutorials"
	url = ""
